### ISSUE TITLE
Unable to use `clear()` method from `ExperimentClient`

### ISSUE THREAD

**Issue by fedejordan** [amplitude/experiment-ios-client#27]
Hi team, we want to integrate Experiment in our project but noticed that we cannot clear the cache for the experiments.

In the docs [it says](https://www.docs.developers.amplitude.com/experiment/sdks/ios-sdk/#clear):
```
/// You can call clear after user logout to clear the variants in cache and storage.
experiment.clear()
```

But the `clear()` method is not present in the `ExperimentClient` protocol [definition](https://github.com/amplitude/experiment-ios-client/blob/main/Sources/Experiment/ExperimentClient.swift#L10).
It's just in the `DefaultExperimentClient` [implementation](https://github.com/amplitude/experiment-ios-client/blob/main/Sources/Experiment/ExperimentClient.swift#L120), which is internal in the package and unable to access from the consumer.

Can you do a fix to make it available for the consumer?
Thanks in advance

**Comment by bgiori** [comment]
Fixed in version 1.9.1, thanks!
