### ISSUE TITLE
Any support/plan of Privacy Manifest?

### ISSUE THREAD

**Issue by dp221125** [amplitude/experiment-ios-client#47]
This SDK is using the [User Defaults API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
So, I was wondering if the Privacy Manifest update will be introduce in following updates

**Comment by bgiori** [comment]
Hi @dp221125, thanks for submitting this issue. Yes we are planning to add a privacy manifest. Currently high priority, should be included in the next release later this month

**Comment by hatchedlabs-tomasz-frontczak** [comment]
Hi @bgiori any update on that?

**Comment by bgiori** [comment]
https://github.com/amplitude/experiment-ios-client/pull/48

**Comment by bgiori** [comment]
Released in `1.13.3`
