### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by juanuribeo13** [amplitude/experiment-ios-client#53]
I'm seeing a compilation error saying that `Multiple commands produce PrivacyInfo.xcprivacy` after updating the `AmplitudeExperiment` pod to version `1.13.3`

**Comment by crleona** [comment]
Hi @juanuribeo13, this was fixed in https://github.com/amplitude/experiment-ios-client/pull/52, which I just released in [1.13.4](https://github.com/amplitude/experiment-ios-client/releases/tag/v1.13.4).

**Comment by juanuribeo13** [comment]
I was able to update to `1.13.4` successfully, thank you @crleona for que quick fix 🙂
